#!/bin/bash
# =================================================================
# doca_offline_run.sh
# NVIDIA DOCA Offline Bundle Creator — ARM64 / GB300 Edition
#
# Generates a self-extracting .run installer via makeself.
# Run on an INTERNET-CONNECTED ARM64 Ubuntu 24.04 machine
# that already has the DOCA Local Repo .deb registered.
#
# Usage:
#   1. Place your doca-host_*.deb in the same directory.
#   2. sudo ./doca_offline_run.sh
#   3. Transfer the generated .run file to the offline target.
#   4. On target: chmod +x <file>.run && sudo ./<file>.run
# =================================================================
set -euo pipefail

# ── Colour helpers ────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'
info()    { echo -e "${CYAN}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()     { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
step()    { echo -e "\n${BOLD}$*${NC}"; }

# ── Configuration ─────────────────────────────────────────────────
SOURCE_DEB="doca-host_3.2.1-044413-25.10-ubuntu2404_arm64.deb"
WORK_DIR="doca_installer_payload"
OUTPUT_RUN="doca-3.2.1-offline-gb300-arm64.run"
TARGET_KERNEL="6.8.0-1025-nvidia"

# Core packages required for DKMS + OFED kernel module compilation
CORE_PKGS=(
    build-essential dkms gcc make libc6-dev patch pkg-config
    libelf-dev binutils python3 flex bison graphviz
    pciutils ethtool lsof libltdl7
)

# ── Pre-flight checks ─────────────────────────────────────────────
[[ $EUID -eq 0 ]] || die "Please run as root: sudo $0"
[[ -f "$SOURCE_DEB" ]] || die "Source file not found: $SOURCE_DEB\n       Place the DOCA Local Repo .deb in this directory first."
command -v makeself >/dev/null 2>&1 || die "'makeself' not found. Run: sudo apt install makeself"
command -v apt-rdepends >/dev/null 2>&1 || { info "Installing apt-rdepends..."; apt-get install -y apt-rdepends; }

# Verify the DOCA Local Repo is registered in APT
apt-cache show doca-host &>/dev/null || \
    die "DOCA repo not found in APT. Register it first:\n  sudo dpkg -i <doca-repo-*.deb> && sudo apt-get update"

# ── Workspace ─────────────────────────────────────────────────────
step "[1/4] Preparing workspace..."
rm -rf "$WORK_DIR"
mkdir -p "$WORK_DIR"/{deps,headers}
success "Workspace ready: ./$WORK_DIR"

# ── Download core build tools ─────────────────────────────────────
step "[2/4] Downloading build tools & system dependencies..."
cd "$WORK_DIR/deps"

info "Downloading core build packages..."
for pkg in "${CORE_PKGS[@]}"; do
    apt-get -o APT::Sandbox::User=root download "$pkg" 2>/dev/null \
        && echo "  ✓ $pkg" \
        || warn "  Skipped: $pkg"
done

info "Resolving recursive DOCA dependencies (this may take several minutes)..."
DEPS_LIST=$(apt-rdepends doca-host doca-all doca-tools doca-extra 2>/dev/null \
    | grep -v "^ " \
    | grep -Ev "^debconf$|^doca-repo-|^$" \
    || true)

TOTAL=0; SKIPPED=0
for pkg in $DEPS_LIST; do
    if apt-get -o APT::Sandbox::User=root download "$pkg" 2>/dev/null; then
        TOTAL=$((TOTAL + 1))
    else
        SKIPPED=$((SKIPPED + 1))
    fi
done
success "Downloaded $TOTAL DOCA dependency packages. ($SKIPPED skipped / already satisfied)"

# Remove zero-byte stub files that apt-get download sometimes creates
find . -maxdepth 1 -name "*.deb" -size 0 -delete
cd ../..

# ── Kernel headers ────────────────────────────────────────────────
step "[3/4] Downloading Kernel Headers ($TARGET_KERNEL)..."
cd "$WORK_DIR/headers"
apt-get -o APT::Sandbox::User=root download \
    "linux-headers-${TARGET_KERNEL}" \
    "linux-headers-${TARGET_KERNEL}-64k" \
    2>/dev/null || warn "One or more header variants not available."
success "Kernel headers staged."
cd ../..

# ── Generate embedded install.sh ──────────────────────────────────
step "[4/4] Generating self-extracting payload..."
cp "$SOURCE_DEB" "$WORK_DIR/"

cat << 'INSTALL_EOF' > "$WORK_DIR/install.sh"
#!/bin/bash
# ---------------------------------------------------------------
# NVIDIA DOCA 3.2.1 — Offline Installer (GB300 / ARM64)
# Auto-generated by doca_offline_run.sh — do not edit manually.
# ---------------------------------------------------------------
set -e
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
info()    { echo -e "\033[0;36m[INFO]\033[0m $*"; }
success() { echo -e "${GREEN}[OK]\033[0m  $*"; }
warn()    { echo -e "${YELLOW}[WARN]\033[0m $*"; }

echo "-----------------------------------------------"
echo "  NVIDIA DOCA 3.2.1 Offline Installer (GB300)  "
echo "-----------------------------------------------"

# Step 1: Install headers & build tools
info "[1/3] Installing Kernel Headers and Build Tools..."
dpkg -i ./headers/*.deb 2>/dev/null || warn "Some headers skipped (may already be installed)."
dpkg -i ./deps/*.deb    2>/dev/null || warn "Some deps skipped (dependency ordering — see Step fix below)."

# Fix any broken dependency ordering from bulk dpkg install
apt-get install -f -y \
    -o Dir::Etc::sourcelist="/dev/null" \
    -o Dir::Etc::sourceparts="-" \
    2>/dev/null || warn "apt-get -f encountered issues; continuing..."
success "Base environment ready."

# Step 2: Set up local DOCA repo
info "[2/3] Configuring Local DOCA Repository (offline, GPG-bypassed)..."
LOCAL_DEB=$(ls doca-host_*.deb 2>/dev/null | head -n 1)
[[ -n "$LOCAL_DEB" ]] || { echo -e "${RED}[ERROR]${NC} doca-host .deb not found in payload."; exit 1; }

dpkg -i "$LOCAL_DEB"

# Remove online list to prevent GPG / connectivity failures
rm -f /etc/apt/sources.list.d/doca.list 2>/dev/null || true

REPO_PATH=$(ls -d /var/doca-repo-* 2>/dev/null | head -n 1)
[[ -n "$REPO_PATH" ]] || { echo -e "${RED}[ERROR]${NC} DOCA repo path not found after dpkg install."; exit 1; }

echo "deb [trusted=yes] file:${REPO_PATH} ./" \
    > /etc/apt/sources.list.d/doca-local-offline.list

apt-get update \
    -o Dir::Etc::sourcelist="sources.list.d/doca-local-offline.list" \
    -o Dir::Etc::sourceparts="-" \
    -o APT::Get::List-Cleanup="0"
success "Local repo configured: ${REPO_PATH}"

# Step 3: Install DOCA stack
info "[3/3] Installing DOCA Stack (host, all, tools, extra)..."
apt-get install -y \
    --allow-unauthenticated \
    --allow-downgrades \
    --no-install-recommends \
    doca-host doca-all doca-tools doca-extra

info "Enabling OpenIB services..."
/etc/init.d/openibd restart 2>/dev/null || true
systemctl enable openibd   2>/dev/null || true

echo ""
echo "-----------------------------------------------"
echo -e "${GREEN} INSTALLATION COMPLETED SUCCESSFULLY${NC}"
echo "-----------------------------------------------"
echo " ⚠  IMPORTANT: Please REBOOT your system now."
echo " After reboot, verify with:"
echo "   /opt/mellanox/doca/tools/doca-info"
echo "   ibstat"
echo "-----------------------------------------------"
INSTALL_EOF

chmod +x "$WORK_DIR/install.sh"

# ── Build the .run file ───────────────────────────────────────────
makeself --needroot "./$WORK_DIR" "$OUTPUT_RUN" "NVIDIA DOCA 3.2.1 Offline Installer" ./install.sh

# ── Final summary ─────────────────────────────────────────────────
FILESIZE=$(du -sh "$OUTPUT_RUN" | cut -f1)
echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}  Self-Extracting Package Created!${NC}"
echo -e "${GREEN}================================================${NC}"
echo -e "  File : ${BOLD}$OUTPUT_RUN${NC}  ($FILESIZE)"
echo ""
echo -e "  ${BOLD}Deploy to offline target:${NC}"
echo -e "    scp $OUTPUT_RUN user@target-host:/tmp/"
echo -e "    ssh user@target-host"
echo -e "    chmod +x /tmp/$OUTPUT_RUN && sudo /tmp/$OUTPUT_RUN"
echo -e "${GREEN}================================================${NC}"
